[#9] 회원 가입 프로세스 구현
f-lab-edu/used-trading-market pull request #10
Opened 2024-03-09 10:33 UTC by hyunsb

## Description
회원 가입 프로세스를 구현한다.
- `POST` `/api/v1/members` `HTTP 1.1`
- 사용자는 regionId, email, password, nickname을 Application/json 타입으로 ResponseBody에 담아 요청한다.
- Driving Adapter(hadler)는 각 데이터에 대한 검증을 수행한 이후 UseCase에 따른 Service를 호출한다.
- Service는 regionId 검증, 이메일 중복체크, password 암호화를 수행한 뒤 도메인을 생성하고, outputPort를 통해 회원 정보를 저장한다.
- Driven Adapter는 도메인 객체를 Persistence Entity로 파싱하여 DB 저장 작업을 수행한다.

<br>

## Issue
- #9 

<br>
resolved: #9

2024-03-11 15:32 UTC, f-lab-justin requested changes
@hyunsb 
확인 부탁드립니다~!

2024-03-11 15:32 UTC, f-lab-justin commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private final ValidateRegionUseCase validateRegionUseCase;
@hyunsb 
ValidateRegionUseCase를 UseCase로 뺀 이유가 있을까요??

2024-03-11 15:32 UTC, f-lab-justin commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private void setEncryptedPassword(MemberForCreate memberForCreate) {
@hyunsb 
다음 코드는 MemberForCreate의 필드인 encryptedPassword의 로직이 도메인 바깥으로 노출됩니다. 
set함수를 안사용하고 작성할 수 있게 수정한다면 어떨까요?

2024-03-11 15:32 UTC, f-lab-justin commented on used-trading-bootstrap/src/main/resources/ValidationMessages.properties
> +validation.constraints.member.regionId.NotNull.message  = \uC9C0\uC5ED\uC740 \uD544\uC218 \uAC12\uC785\uB2C8\uB2E4.
@hyunsb 
호오..요렇게 나오는거 맞나요???

2024-03-11 15:32 UTC, f-lab-justin commented on used-trading-domain/src/main/java/org/flab/hyunsb/domain/member/MemberForCreate.java
> +public class MemberForCreate {
@hyunsb 
위의 request/response 객체와 일관성을 맞춘다면 요 엔티티에서 toMember() mapper를 넣어주면 어떨까요??

2024-03-12 04:29 UTC, hyunsb commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private final ValidateRegionUseCase validateRegionUseCase;
단위 테스트 시 Mock 구현체를 생성하고, 주입해 주기 위해서 UseCase 인터페이스와 의존관계를 형성했습니다!

2024-03-12 04:59 UTC, hyunsb commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private void setEncryptedPassword(MemberForCreate memberForCreate) {
초기에 `setEncryptedPassword` 메서드의 파라매터로 `Encryptor`을 넘겨주고 내부에서 암호화 후, 
`MemberForCreate`의 `password`필드를 수정하는 방식으로 코드를 작성했었습니다.

위 처럼 코드를 작성했을 시,
Encryptor은 애플리케이션 모듈에 존재하기 때문에 domain모듈에서 application모듈로의 의존 방향이 생겨버리게 되었습니다. 따라서 application 모듈에서 암호화 진행 후 필드 값을 변경하는 식으로 코드를 작성했습니다.

멘토님 코드리뷰를 받고 다시 생각해봤는데, Encryptor 인터페이스를 domain모듈에 선언하고,
구체 클래스는 applicaiton모듈에 선언 및 빈으로 생성하여 application 코드에서 Encryptor 구체 클래스를 넘겨주는 방식은 어떨까 라는 생각이 들었습니다.
```java
// domain - MemberForCreate.class
private void setEncryptedPassword(Encryption encryption) { ... }

// domain - Encryptor.class
public interface Encryptor { ... }
```
```java
// application - MemberService.class
MemberForCreate.setEncryptedPassword(passwordEncryptor)

// domain - PasswordEncryptor.class
public class PasswordEncryptor { ... }
```

2024-03-12 05:03 UTC, hyunsb commented on used-trading-bootstrap/src/main/resources/ValidationMessages.properties
> +validation.constraints.member.regionId.NotNull.message  = \uC9C0\uC5ED\uC740 \uD544\uC218 \uAC12\uC785\uB2C8\uB2E4.
이게 `.properties`파일에 선언된 한글을 유니코드로 변경하지 않으니까 HTTP ResponseBody 부분에서 깨지더라구요.
IDE에서는 한글로 잘 보이던데 해결 방법을 찾아보겠습니다..!

2024-03-12 05:17 UTC, hyunsb commented on used-trading-domain/src/main/java/org/flab/hyunsb/domain/member/MemberForCreate.java
> +public class MemberForCreate {
제가 잘 이해했는지 모르겠는데 MemberForCreate의 toMember() mapper를 두고
```java
// bootstrap - MemberPersistenceAdapter.class
@Override
public Member saveMember(MemberForCreate memberForCreate) {
    MemberEntity memberEntity = MemberEntity.from(memberForCreate);
    memberEntity = memberRepository.save(memberEntity);

    return memberEntity.toDomain();
}
```
이부분에서 MemberForCreate를 파라매터로 받아 JpaEntity로 파싱하는 것이 아닌,

MemberForCreate의 toMember() mapper를 통헤 Member로 파싱한 뒤, 파라매터로 넘겨주고
아래처럼 Member를 JPA Entity로 파싱하는 방법을 사용하라는 말씀이 맞을까요? 
```java
// bootstrap - MemberPersistenceAdapter.class
@Override
public Member saveMember(Member member) {
    MemberEntity memberEntity = MemberEntity.from(member);
    // ...
}
```

2024-03-14 13:08 UTC, hyunsb commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private void setEncryptedPassword(MemberForCreate memberForCreate) {
피드백을 반영하여 Member 클래스에서 MemberForCreate를 파라매터로 받는 정적 팩토리 메서드를 생성하고,
Member 객체 생성 시점에 비밀번호를 암호화 하도록 변경했습니다.

Commit: [3695cf6](https://github.com/f-lab-edu/used-trading-market/pull/10/commits/3695cf63dc641286ee6d0c0fbb895f23f1c91514)

---

### 질문
현재의 구조로는 Member 클래스 로드 시점에 Encryptor를 초기화하는데, 
Member와 PasswordEncryptor가 너무 강하게 결합되어 있다는 생각이 들었습니다.

프로젝트에서 오로지 Member 도메인에서만 PasswordEncryptor가 사용되는데 
이러한 경우에는 이정도의 결합은 허용하는 것이 옳은지 궁금합니다!

```java
public record Member(Long id, Long regionId, String email, String password, String nickname) {

    private static final Encryptor ENCRYPTOR = PasswordEncryptor.getInstance();

    public static Member from(MemberForCreate memberForCreate) {
        return new Member(
            null,
            memberForCreate.regionId(),
            memberForCreate.email(),
            encryptPassword(memberForCreate.password()),
            memberForCreate.nickname()
        );
    }

    private static String encryptPassword(String password) {
        return ENCRYPTOR.encrypt(password);
    }
}
```

2024-03-14 13:23 UTC, hyunsb commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private final ValidateRegionUseCase validateRegionUseCase;
이전의 프로젝트를 미루어봤을 때, 각 Service에서 검증 로직이 빈번하게 발생할 것으로 예상했습니다.
이전 프로젝트에서는 결국 검증 로직 때문에 거의 모든 Service가 서로 의존하는 꼴이 되어버렸습니다.

따라서 외부 서비스를 호출하는 검증은 validator 인터페이스를 통하도록 수정했봤습니다.
이번 프로젝트를 진행하며 검증로직을 validator로 분리하는 것이 적합하지 않다고 판단되면 다시 고민하고 수정해보겠습니다!

Commit: [4b77eda](https://github.com/f-lab-edu/used-trading-market/pull/10/commits/4b77eda388d7d0de60184470fd87ac2d7ea1371b)

2024-03-19 12:40 UTC, f-lab-justin commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/MemberService.java
> +    private void setEncryptedPassword(MemberForCreate memberForCreate) {
@hyunsb 
넵~ 유틸성 클래스들을 static으로 들고 처리하는 건 괜찮다고 생각합니다~!

2024-03-19 12:43 UTC, f-lab-justin approved these changes
@hyunsb 
LGTM

2024-03-19 13:09 UTC, merged