[#11] 로그인 및 토큰 인증 프로세스 구현
f-lab-edu/used-trading-market pull request #12
Opened 2024-03-23 15:16 UTC by hyunsb

## Description
로그인 프로세스를 구현한다.
- `POST` `/api/v1/members/login` `HTTP 1.1`
- 사용자는 email, password를 Application/json 타입으로 ResponseBody에 담아 요청한다.
- Driving Adapter(hadler)는 각 데이터에 대한 검증을 수행한 이후 UseCase에 따른 Service를 호출한다.
- Service는 이메일에 해당하는 데이터를 조회하고 비밀번호 검증을 수행한다.
- 로그인 성공 시 JWT를 생성하여 HTTP header에 담아 반환한다.

<br>

## Issue
- #11 

<br>
resolved: #11

2024-03-23 15:20 UTC, hyunsb commented on used-trading-domain/src/main/java/org/flab/hyunsb/domain/member/Member.java
> +    }
이부분을 아래 처럼 구현하고 싶은데 고민이 있습니다.
```java
 public void tryLogin(MemberForLogin memberForLogin) {
        // 비밀번호가 일치하지 않으면
       throws Exception();
    }
```

1. 도메인 모듈에서 발생하는 예외를 ControllerAdvice 까지 전파시켜도 되는가?
2. 이메일 검증은 외부에서 자연스럽게 이미 진행했는데 도메인 내부에서 email 데이터까지 받을 필요가 있는가?

2024-03-23 15:22 UTC, hyunsb commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/ActorTokenService.java
> +    private final SecretKey secretKey;
단위 테스트 시 현재 시간 데이터를 컨트롤할 수 없다고 판단하여 현재 Date를 반환하는 인터페이스를 두었습니다. 단위 테스트에서 토큰의 유효기간을 검증하는 데 유용하게 사용되었지만 이게 괜찮은 방법인지 의심스럽습니다.

2024-03-26 13:03 UTC, f-lab-justin commented on used-trading-domain/src/main/java/org/flab/hyunsb/domain/member/Member.java
> +    }
@hyunsb 
1.도메인 모듈에서 발생하는 예외를 ControllerAdvice 까지 전파시켜도 되는가?
=> 물론입니다. 도메인은 코어에 있는 영역이니까요!

2. 이메일 검증은 외부에서 자연스럽게 이미 진행했는데 도메인 내부에서 email 데이터까지 받을 필요가 있는가?
=> 요 부분은 이해를 하지 못했습니다만 member에서 이메일을 저장하지 않나요??

2024-03-26 13:17 UTC, f-lab-justin requested changes
@hyunsb 
먼가 mock 서비스들이 점점 커지는 느낌이네요~!!

2024-03-26 13:17 UTC, f-lab-justin commented on used-trading-application/src/main/java/org/flab/hyunsb/application/service/ActorTokenService.java
> +    private final SecretKey secretKey;
@hyunsb 
참고하세요~!
https://www.baeldung.com/java-override-system-time

2024-03-26 13:17 UTC, f-lab-justin commented on used-trading-bootstrap/src/main/java/org/flab/hyunsb/bootstrap/rest/adapter/MemberRestAdapter.java
> +        return ResponseEntity.ok()
@hyunsb 
요 함수에서는 Object를 리턴할 수 밖에 없을까요??
추가적으로 ResponseEntity를 생략할수는 없을까요??

2024-03-26 16:27 UTC, hyunsb commented on used-trading-bootstrap/src/main/java/org/flab/hyunsb/bootstrap/rest/adapter/MemberRestAdapter.java
> +        return ResponseEntity.ok()
초기에 아래의 코드로 작성했었습니다!
메서드는 void 이지만 실제로는 ResponseEntity를 반환하기에 
어색하다고 생각해서 지금의 코드로 변경했는데 기존의 코드가 더 가독성이 좋을까요??
```java
@ResponseStatus(HttpStatus.OK)
@PostMapping("/login")
public void login(@Valid @RequestBody MemberLoginRequest memberLoginRequest,
    HttpServletResponse response) {
        
    String accessToken = loginUseCase.login(memberLoginRequest.toMemberForLogin());
    response.setHeader(ACTOR_TOKEN_HEADER, accessToken);
}
```

2024-04-09 08:59 UTC, hyunsb commented on used-trading-domain/src/main/java/org/flab/hyunsb/domain/member/Member.java
> +    }
> 요 부분은 이해를 하지 못했습니다만 member에서 이메일을 저장하지 않나요??

로그인을 위해 서비스에서 email 과 password를 파라매터로 받고, findByEmail을 수행 하여 Member 객체를 불러옴으로써 email에 대한 검증은 끝났다 라고 생각했습니다. 따라서 Member객체에 password 값만 전달하여 비밀번호가 일치하는지 확인하는 로직을 수행하도록 했습니다. 
```java
Member member = memberOutputPort.findByEmail(email);
boolean result = member.isMatchingPassword(password);
``` 
도메인에서 발생하는 예외를 controllerAdvice에서 처리한다는게 예외를 너무 전파시키는 것이 아닌가라는 생각을 해서 비밀번호가 일치하는지를 boolean 값으로 받고, 결과를 service에서 처리하는 방식을 사용했습니다. 

멘토님의 피드백에 따라 도메인에서 예외를 발생하도록 리팩터링하고 Password에 대한 기능을 캡슐화 함으로써 해결했습니다!

Commit: [e7232ee](https://github.com/f-lab-edu/used-trading-market/pull/12/commits/e7232ee02853b3add377e1f4a7d644fc6c86eb9a)

2024-04-09 20:23 UTC, merged