[#1] 프로젝트 구조 생성 및 샘플 코드 작성
f-lab-edu/used-trading-market pull request #2
Opened 2024-02-09 19:43 UTC by hyunsb

## Description
헥사고날 아키텍처를 기반으로 멀티 모듈 프로젝트 구조를 생성한다.
샘플 코드를 작성하여 기능 생성 플로우를 확인한다.

### 모듈 의존성 다이어그램
![image](https://github.com/f-lab-edu/used-trading-market/assets/96504592/5b7f6d9c-692d-4e9d-9b30-63d9b6413312)

<br>

## Issue
- #1 

<br>
resolved: #1

2024-02-12 15:05 UTC, f-lab-justin requested changes

2024-02-12 15:05 UTC, f-lab-justin commented on used-trading-bootstrap/src/main/java/org/flab/hyunsb/bootstrap/rest/adapter/ProductRestAdapter.java
> +    public ResponseEntity<ProductCreateResponse> createProduct(
@정현수
ResponseEntity도 생략해볼 수 있을까요??

```java
public ProductCreateResponse createProduct() {
    // 블라블라
} 
```

HttpStatus Code는 어떻게 처리할 수 있을까요??

2024-02-12 15:05 UTC, f-lab-justin commented on used-trading-framework/src/main/java/org/flab/hyunsb/framework/persistence/adapter/ProductPersistenceAdapter.java
> +        Optional<ProductEntity> optionalProductEntity = productRepository.findById(id);
@정현수 
chaining으로 하나의 코드구조로 리턴하게 작성할 수도 있을까요?

2024-02-14 04:08 UTC, hyunsb commented on used-trading-framework/src/main/java/org/flab/hyunsb/framework/persistence/adapter/ProductPersistenceAdapter.java
> +        Optional<ProductEntity> optionalProductEntity = productRepository.findById(id);
```JAVA
return productRepository.findById(id)
        .map(mapper::toDomain)
        .or(Optional::empty);
```
체이닝을 통해 한줄의 코드로 단축시켰습니다!

2024-02-14 04:12 UTC, hyunsb commented on used-trading-bootstrap/src/main/java/org/flab/hyunsb/bootstrap/rest/adapter/ProductRestAdapter.java
> +    public ResponseEntity<ProductCreateResponse> createProduct(
```JAVA
@ResponseStatus(HttpStatus.CREATED)
```
`ResponseStatus` 어노테이션을 사용하여 처리하도록 변경했습니다.
해당 어노테이션의 단점은 `ResponseEntity` 객체를 사용하는 것보다 Http 헤더의 설정이 유연하지 않다는 점입니다.
헤더 설정이 따로 필요하지 않은 경우 해당 방법이 가독성이 좋다고 생각되어 해당 방식을 사용하기로 했습니다.

감사합니다!

2024-02-14 04:14 UTC, merged