[#3] 데이터베이스 테이블 설계, ORM 엔티티 생성
f-lab-edu/used-trading-market pull request #4
Opened 2024-03-05 04:40 UTC by hyunsb

## Description
- 데이터베이스 테이블을 설계한다.
- ORM 엔티티를 생성하고 테스트 환경을 구축한다.

### ERD
![image](https://github.com/f-lab-edu/used-trading-market/assets/96504592/e5a0982d-ed12-4793-a1c0-253b32e0dd1f)

<br>

## Issue
- #3 

<br>
resolved: #3

2024-03-05 13:12 UTC, f-lab-justin requested changes
@hyunsb 
제가 코딩할 때 생각하는 기본 규칙(?)들입니다. 저는 요런 요소들만 최대한 지키려고 해도 훌륭한 코드가 될 거라고 생각해요.

- high cohesion, low coupling
- null은 최대한 안보이도록..
- 분기문 최소화(if가 싫어요)

2024-03-05 13:12 UTC, f-lab-justin commented on used-trading-framework/src/test/java/org/flab/hyunsb/framework/MemberRepositoryTest.java
> +        return new MemberEntity(null, testRegion, email, password, nickname);
@hyunsb 
null보다는 factory메소드등을 통해 최대한 null을 코드상에서 없애보면 좋을 것 같습니다.

2024-03-06 03:01 UTC, hyunsb commented on used-trading-framework/src/test/java/org/flab/hyunsb/framework/MemberRepositoryTest.java
> +        return new MemberEntity(null, testRegion, email, password, nickname);
이전 멘토링에서 멘토님이 해주셨던 피드백처럼 domain 모듈에서 Create 유즈케이스를 위한 클래스를 선언할 예정입니다.
``` java
public class MemberForCreate {
    private String email;
    private String password;
    private String nickname;
    //...
}
```
MemberEntity에서 해당 클래스를 인자로 받는 정적 팩토리 메서드를 선언하여 null을 클래스 내부로 숨기려고 합니다.
``` java
public class MemberEntity {
    //...
    public static MemberEntity(MemberForCreate) {
        //...
    }
}
```

2024-03-06 03:02 UTC, hyunsb commented on used-trading-framework/src/test/java/org/flab/hyunsb/framework/MemberRepositoryTest.java
> +        return new MemberEntity(null, testRegion, email, password, nickname);
> high cohesion, low coupling

이게 참 코드를 작성하면서 많은 고민을 하게 만드는 문구인 것 같습니다..

2024-03-06 06:27 UTC, merged